### ISSUE TITLE
Integration of Stuttering Speech Repair System into Batchalign2

### ISSUE THREAD

**Issue by oven521** [TalkBank/batchalign2#2]
Hello, 

I am a member of the team that previously discussed our project with you. We have developed a stuttering speech repair system and are now eager to learn how we can integrate this system into your project. We are fully prepared to work closely with you to ensure a smooth integration.

We look forward to the opportunity to contribute to your project.

**Comment by Jemoka** [comment]
Closing per discussion by email.
