### ISSUE TITLE
Missing picture in Usage file

### ISSUE THREAD

**Issue by JaviAgua** [TalkBank/batchalign2#5]
Hello, Just to let you know that the link "this screenshot" appears to be missing in the reference document: https://talkbank.org/info/BA2-usage.pdf

**Comment by Jemoka** [comment]
thanks for flagging this; will take a look and fix

**Comment by Jemoka** [comment]
The link should now be clickable on the doc; please feel free to clear your cache and try again. Don't hesitate to reopen the issue if you are still having trouble.
