### ISSUE TITLE
Batchalign 2 - Unable to run Whisper Engine / Forced Alignment

### ISSUE THREAD

**Issue by RichardGhiuzan** [TalkBank/batchalign2#6]
I have been using the library version of Batchalign 2 to produce transcripts, and while I've been able to do so, I've been getting a recurrent error whenever trying to run a forced alignment on an existing transcript using the following line of coding:
 
chat = ba.CHATFile(path = "inputfile.cha")
doc = chat.doc
nlp = ba.BatchalignPipeline.new("fa", lang="eng", num_speakers=2)
doc = nlp(chat)
final = ba.CHATFile(doc=doc)
final.write("final.cha")

I get a very lengthy error output, which I can share if needed, but this seems to be the main error:
RuntimeError Traceback (most recent call last) Cell In[38], line 4 
2 chat = ba.CHATFile(path = "inputfile.cha") 
3 doc = chat.doc 
----> 4 nlp = ba.BatchalignPipeline.new("fa", lang="eng", num_speakers=2) 
5 doc = nlp(chat) 
6 final = ba.CHATFile(doc=doc)

[...]

2572 raise ValueError( 2573 "You cannot cast a GPTQ model in a new `dtype`. Make sure to load the model using `from_pretrained` using the desired" 2574 " `dtype` by passing the correct `torch_dtype` argument."

Would anyone have encountered a similar error and know how to solve it? 
Thank you in advance for the time and availability. 
Kind Regards, 
Richard

**Comment by Jemoka** [comment]
Apologies about this! Looking at your script, could you try:

```python
chat = ba.CHATFile(path = "inputfile.cha")
doc = chat.doc
nlp = ba.BatchalignPipeline.new("fa", lang="eng", num_speakers=2)
~~doc = nlp(chat)~~
doc = nlp(**doc**)
final = ba.CHATFile(doc=doc)
final.write("final.cha")
```

However, something is really odd on that none of this should involve GPTQ in any way.

**Comment by RichardGhiuzan** [comment]
Thank you for your response. Unfortunately, I tried running the code you gave me and the same error output was obtained. I should also add that at the bottom of these errors, this error also occurs:

 "RuntimeError: MPS backend out of memory (MPS allocated: 8.99 GB, other allocations: 86.54 MB, max allowed: 9.07 GB). Tried to allocate 1.17 MB on private pool. Use PYTORCH_MPS_HIGH_WATERMARK_RATIO=0.0 to disable upper limit for memory allocations (may cause system failure)."

Please let me know if you have further solutions.

**Comment by Jemoka** [comment]
that looks like a hardware limitation; can you please tell me how much memory you have on your system?

**Comment by RichardGhiuzan** [comment]
I have a Mac Air with 8GB memory.

**Comment by Jemoka** [comment]
sadly I don't think that would load on that machine; any chance you can try on a machine with at least 16GB of memory? feel free to reopen if needed.
