### ISSUE TITLE
Error when using morphotag on a .cha file

### ISSUE THREAD

**Issue by batchenoz** [TalkBank/batchalign2#9]
Hello, it's my first time using batchalign.
I tried to run `morphotag` on a `.cha` file, and I got this error:
`Unexpected Batchalign error when parsing CHAT: line='*DOR:   ima. 0_2443', error='string index out of range'`.

Is there anything I'm doing wrong?
This is the command I ran: `batchalign morphotag --lang=heb . output`
and the cha file contains `@Languages:	heb`
Thanks

**Comment by Jemoka** [comment]
great to hear. closing; feel free to reopen if needed.
